export const supportedViewOAuthScopes = [
  'view_api_clients',
  'view_audit_log',
  'view_cart_discounts',
  'view_categories',
  'view_customer_groups',
  'view_customers',
  'view_discount_codes',
  'view_import_containers',
  'view_key_value_documents',
  'view_messages',
  'view_order_edits',
  'view_orders',
  'view_payments',
  'view_products',
  'view_project_settings',
  'view_published_products',
  'view_shipping_methods',
  'view_shopping_lists',
  'view_states',
  'view_stores',
  'view_tax_categories',
  'view_types',
];

export const supportedManageOAuthScopes = [
  'manage_api_clients',
  'manage_audit_log',
  'manage_cart_discounts',
  'manage_categories',
  'manage_customer_groups',
  'manage_customers',
  'manage_discount_codes',
  'manage_extensions',
  'manage_import_containers',
  'manage_key_value_documents',
  'manage_order_edits',
  'manage_orders',
  'manage_payments',
  'manage_products',
  'manage_project_settings',
  'manage_shipping_methods',
  'manage_shopping_lists',
  'manage_states',
  'manage_stores',
  'manage_subscriptions',
  'manage_tax_categories',
  'manage_types',
];

export const supportedOAuthScopes = [
  ...supportedViewOAuthScopes,
  ...supportedManageOAuthScopes,
];
