import type { TCartDraftGraphql, TCartDraftRest } from '../../../types';
import * as presets from './eagle-heavy-lift-technologies-inc-us-cart-2';

describe(`with eagleHeavyLiftTechnologiesIncUsCart2 preset`, () => {
  it(`should return a eagleHeavyLiftTechnologiesIncUsCart2 preset when built for rest`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart2Preset = presets
      .restPreset()
      .build();
    expect(eagleHeavyLiftTechnologiesIncUsCart2Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-2",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-red",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-blue",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-green",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": "Unit 456",
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a eagleHeavyLiftTechnologiesIncUsCart2 preset when built for graphql`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart2Preset = presets
      .graphqlPreset()
      .build();
    expect(eagleHeavyLiftTechnologiesIncUsCart2Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-2",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-red",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-blue",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-green",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": "Unit 456",
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a eagleHeavyLiftTechnologiesIncUsCart2 preset when built for legacy rest`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart2Preset = presets
      .compatPreset()
      .buildRest<TCartDraftRest>();
    expect(eagleHeavyLiftTechnologiesIncUsCart2Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-2",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-red",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-blue",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-green",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": "Unit 456",
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a eagleHeavyLiftTechnologiesIncUsCart2 preset when built for legacy graphql`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart2Preset = presets
      .compatPreset()
      .buildGraphql<TCartDraftGraphql>();
    expect(eagleHeavyLiftTechnologiesIncUsCart2Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-2",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-red",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-blue",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": {
              "key": "us-large-customers",
              "typeId": "channel",
            },
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "yy123-qr-green",
            "supplyChannel": {
              "key": "us-warehouse",
              "typeId": "channel",
            },
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": "Unit 456",
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
