import type { TCartDraft } from '../../../types';
import eagleHeavyLiftTechnologiesIncUsCart1 from './eagle-heavy-lift-technologies-inc-us-cart-1';

describe(`with eagleHeavyLiftTechnologiesIncUsCart1 preset`, () => {
  it(`should return a eagleHeavyLiftTechnologiesIncUsCart1 preset`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart1Preset =
      eagleHeavyLiftTechnologiesIncUsCart1().build<TCartDraft>();
    expect(eagleHeavyLiftTechnologiesIncUsCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a eagleHeavyLiftTechnologiesIncUsCart1 preset when built for graphql`, () => {
    const eagleHeavyLiftTechnologiesIncUsCart1PresetGraphql =
      eagleHeavyLiftTechnologiesIncUsCart1().buildGraphql<TCartDraft>();
    expect(eagleHeavyLiftTechnologiesIncUsCart1PresetGraphql)
      .toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": undefined,
        "businessUnit": {
          "key": "eagle-heavy-lift-technologies-inc-us",
          "typeId": "business-unit",
        },
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "michael-williams@ehlt.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "eagle-heavy-lift-technologies-inc-us-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "eee123-qr-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "789",
          "building": "A",
          "city": "New York",
          "company": "Eagle Heavy Lift Technologies Inc. NY",
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "eagle-heavy-lift-technologies-inc-us-ny-1",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "10001",
          "region": "New York",
          "salutation": undefined,
          "state": "New York",
          "streetName": "Broadway",
          "streetNumber": "123",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "us-large-customers",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
