import type { TCartDraft } from '../../../types';
import lifttechSolutionsLtdEsCart1 from './lifttech-solutions-ltd-es-cart-1';

describe(`with lifttechSolutionsLtdEsCart1 preset`, () => {
  it(`should return a lifttechSolutionsLtdEsCart1 preset`, () => {
    const lifttechSolutionsLtdEsCart1Preset =
      lifttechSolutionsLtdEsCart1().build<TCartDraft>();
    expect(lifttechSolutionsLtdEsCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "567",
          "building": "F",
          "city": "Madrid",
          "company": "LiftTech Solutions Ltd ES",
          "country": "ES",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "lifttech-solutions-ltd-es",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "28013",
          "region": "Community of Madrid",
          "salutation": undefined,
          "state": "Community of Madrid",
          "streetName": "Calle Mayor",
          "streetNumber": "101",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "ES",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "sofia-lopez@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-es-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "567",
          "building": "F",
          "city": "Madrid",
          "company": "LiftTech Solutions Ltd ES",
          "country": "ES",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "lifttech-solutions-ltd-es",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "28013",
          "region": "Community of Madrid",
          "salutation": undefined,
          "state": "Community of Madrid",
          "streetName": "Calle Mayor",
          "streetNumber": "101",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "spain",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a lifttechSolutionsLtdEsCart1 preset when built for graphql`, () => {
    const lifttechSolutionsLtdEsCart1PresetGraphql =
      lifttechSolutionsLtdEsCart1().buildGraphql<TCartDraft>();
    expect(lifttechSolutionsLtdEsCart1PresetGraphql).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "567",
          "building": "F",
          "city": "Madrid",
          "company": "LiftTech Solutions Ltd ES",
          "country": "ES",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "lifttech-solutions-ltd-es",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "28013",
          "region": "Community of Madrid",
          "salutation": undefined,
          "state": "Community of Madrid",
          "streetName": "Calle Mayor",
          "streetNumber": "101",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "ES",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "sofia-lopez@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-es-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "jjj890-op-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": "567",
          "building": "F",
          "city": "Madrid",
          "company": "LiftTech Solutions Ltd ES",
          "country": "ES",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": undefined,
          "id": undefined,
          "key": "lifttech-solutions-ltd-es",
          "lastName": undefined,
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "28013",
          "region": "Community of Madrid",
          "salutation": undefined,
          "state": "Community of Madrid",
          "streetName": "Calle Mayor",
          "streetNumber": "101",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "spain",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
