import type { TCartDraftGraphql, TCartDraftRest } from '../../../types';
import * as presets from './lifttech-solutions-ltd-cart-1';

describe(`with lifttechSolutionsLtdCart1 preset`, () => {
  it(`should return a lifttechSolutionsLtdCart1 preset when built for rest`, () => {
    const lifttechSolutionsLtdCart1Preset = presets.restPreset().build();
    expect(lifttechSolutionsLtdCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "william-taylor@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "de-fr-uk",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a lifttechSolutionsLtdCart1 preset when built for graphql`, () => {
    const lifttechSolutionsLtdCart1Preset = presets.graphqlPreset().build();
    expect(lifttechSolutionsLtdCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "william-taylor@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "de-fr-uk",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a lifttechSolutionsLtdCart1 preset when built for legacy rest`, () => {
    const lifttechSolutionsLtdCart1Preset = presets
      .compatPreset()
      .buildRest<TCartDraftRest>();
    expect(lifttechSolutionsLtdCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "william-taylor@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "de-fr-uk",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a lifttechSolutionsLtdCart1 preset when built for legacy graphql`, () => {
    const lifttechSolutionsLtdCart1Preset = presets
      .compatPreset()
      .buildGraphql<TCartDraftGraphql>();
    expect(lifttechSolutionsLtdCart1Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "william-taylor@ltsl.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "TrackOnly",
        "itemShippingAddresses": undefined,
        "key": "lifttech-solutions-ltd-cart-1",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-red",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-blue",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "ggg789-uv-green",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Customer",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Liverpool",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "William",
          "id": undefined,
          "key": undefined,
          "lastName": "Taylor",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "L1 5AS",
          "region": "Merseyside",
          "salutation": undefined,
          "state": undefined,
          "streetName": "Duke Street",
          "streetNumber": "32",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "standard-shipping-method",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "de-fr-uk",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
