schema:
  - '${MC_API_URL}/graphql':
      headers:
        Cookie: mcAccessToken=${MC_ACCESS_TOKEN}
        X-Graphql-Target: settings
extensions:
  codegen:
    generates:
      # Generate schema
      schemas/settings.json:
        plugins:
          - introspection
      graphql-types/src/generated/settings.ts:
        plugins:
          - typescript
          - typescript-operations
        config:
          typesPrefix: TMcSettings
          addUnderscoreToArgsType: true
          scalars:
            DateTime: string
            Json: '{ [key: string]: unknown }'
    hooks:
      afterAllFileWrite:
        - prettier --write
        - node ./graphql-types/src/types-post-processor.js --types-prefix=TMcSettings
