import type { TCustomerDraft } from '../../../types';
import ameliaJones from './amelia-jones';

describe(`with ameliaJones preset`, () => {
  it(`should return a ameliaJones preset`, () => {
    const ameliaJonesPreset = ameliaJones().build<TCustomerDraft>();
    expect(ameliaJonesPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Birmingham",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Amelia",
            "id": undefined,
            "key": undefined,
            "lastName": "Jones",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "B3 4BH",
            "region": "West Midlands",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Churchill Way",
            "streetNumber": "59",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "amelia-jones@ltsl.com",
        "externalId": undefined,
        "firstName": "Amelia",
        "isEmailVerified": undefined,
        "key": "amelia-jones",
        "lastName": "Jones",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a ameliaJones preset when built for graphql`, () => {
    const ameliaJonesPresetGraphql =
      ameliaJones().buildGraphql<TCustomerDraft>();
    expect(ameliaJonesPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Birmingham",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Amelia",
            "id": undefined,
            "key": undefined,
            "lastName": "Jones",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "B3 4BH",
            "region": "West Midlands",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Churchill Way",
            "streetNumber": "59",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "amelia-jones@ltsl.com",
        "externalId": undefined,
        "firstName": "Amelia",
        "isEmailVerified": undefined,
        "key": "amelia-jones",
        "lastName": "Jones",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
