import type { TCustomerDraft } from '../../../types';
import avaBrown from './ava-brown';

describe(`with avaBrown preset`, () => {
  it(`should return a avaBrown preset`, () => {
    const avaBrownPreset = avaBrown().build<TCustomerDraft>();
    expect(avaBrownPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Cardiff",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Ava",
            "id": undefined,
            "key": undefined,
            "lastName": "Brown",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "CF10 2DL",
            "region": "Wales",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Queen Street",
            "streetNumber": "72",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "ava-brown@lcs.com",
        "externalId": undefined,
        "firstName": "Ava",
        "isEmailVerified": undefined,
        "key": "ava-brown",
        "lastName": "Brown",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a avaBrown preset when built for graphql`, () => {
    const avaBrownPresetGraphql = avaBrown().buildGraphql<TCustomerDraft>();
    expect(avaBrownPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Cardiff",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Ava",
            "id": undefined,
            "key": undefined,
            "lastName": "Brown",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "CF10 2DL",
            "region": "Wales",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Queen Street",
            "streetNumber": "72",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "ava-brown@lcs.com",
        "externalId": undefined,
        "firstName": "Ava",
        "isEmailVerified": undefined,
        "key": "ava-brown",
        "lastName": "Brown",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
