import type { TCustomerDraft } from '../../../types';
import jamesSmith from './james-smith';

describe(`with jamesSmith preset`, () => {
  it(`should return a jamesSmith preset`, () => {
    const jamesSmithPreset = jamesSmith().build<TCustomerDraft>();
    expect(jamesSmithPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "London",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "James",
            "id": undefined,
            "key": undefined,
            "lastName": "Smith",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "NW1 6XE",
            "region": "Greater London",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Baker Street",
            "streetNumber": "221B",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "james-smith@ehlt.com",
        "externalId": undefined,
        "firstName": "James",
        "isEmailVerified": true,
        "key": "james-smith",
        "lastName": "Smith",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a jamesSmith preset when built for graphql`, () => {
    const jamesSmithPresetGraphql = jamesSmith().buildGraphql<TCustomerDraft>();
    expect(jamesSmithPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "London",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "James",
            "id": undefined,
            "key": undefined,
            "lastName": "Smith",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "NW1 6XE",
            "region": "Greater London",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Baker Street",
            "streetNumber": "221B",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "james-smith@ehlt.com",
        "externalId": undefined,
        "firstName": "James",
        "isEmailVerified": true,
        "key": "james-smith",
        "lastName": "Smith",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
