import type { TCustomerDraft } from '../../../types';
import sophieMueller from './sophie-mueller';

describe(`with sophieMueller preset`, () => {
  it(`should return a sophieMueller preset`, () => {
    const sophieMuellerPreset = sophieMueller().build<TCustomerDraft>();
    expect(sophieMuellerPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Berlin",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sophie",
            "id": undefined,
            "key": undefined,
            "lastName": "Müller",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "10115",
            "region": undefined,
            "salutation": undefined,
            "state": "Berlin",
            "streetName": "Schloßstraße",
            "streetNumber": "30",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "sophie-mueller@ltsl.com",
        "externalId": undefined,
        "firstName": "Sophie",
        "isEmailVerified": undefined,
        "key": "sophie-mueller",
        "lastName": "Müller",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a sophieMueller preset when built for graphql`, () => {
    const sophieMuellerPresetGraphql =
      sophieMueller().buildGraphql<TCustomerDraft>();
    expect(sophieMuellerPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Berlin",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sophie",
            "id": undefined,
            "key": undefined,
            "lastName": "Müller",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "10115",
            "region": undefined,
            "salutation": undefined,
            "state": "Berlin",
            "streetName": "Schloßstraße",
            "streetNumber": "30",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "sophie-mueller@ltsl.com",
        "externalId": undefined,
        "firstName": "Sophie",
        "isEmailVerified": undefined,
        "key": "sophie-mueller",
        "lastName": "Müller",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
