import type { TCustomerDraft, TCustomerDraftGraphql } from '../../../types';
import jenniferSchmidt from './jennifer-schmidt';

describe('with the customer preset `jenniferSchmidt`', () => {
  it('should return a draft when built for Default', () => {
    const customer = jenniferSchmidt().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Potsdam",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Schmidt",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "14467",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Hauptstrasse",
            "streetNumber": "25",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.de",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": undefined,
        "key": "jennifer-schmidt",
        "lastName": "Schmidt",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for Rest', () => {
    const customer = jenniferSchmidt().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Potsdam",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Schmidt",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "14467",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Hauptstrasse",
            "streetNumber": "25",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.de",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": undefined,
        "key": "jennifer-schmidt",
        "lastName": "Schmidt",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for GraphQL', () => {
    const customer = jenniferSchmidt().build<TCustomerDraftGraphql>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Potsdam",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Schmidt",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "14467",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Hauptstrasse",
            "streetNumber": "25",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.de",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": undefined,
        "key": "jennifer-schmidt",
        "lastName": "Schmidt",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
