import type { TCustomerDraft, TCustomerDraftGraphql } from '../../../types';
import samSmith from './sam-smith';

describe('with the preset `samSmith`', () => {
  it('should return a customer draft', () => {
    const customer = samSmith().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
        "additionalAddressInfo": undefined,
        "additionalStreetInfo": undefined,
        "apartment": undefined,
        "building": undefined,
        "city": "sdfdsf",
        "company": undefined,
        "country": "GB",
        "custom": undefined,
        "department": undefined,
        "email": undefined,
        "externalId": undefined,
        "fax": undefined,
        "firstName": "Saumya",
        "id": undefined,
        "key": "sam-smith-address-1",
        "lastName": "Goel",
        "mobile": undefined,
        "pOBox": undefined,
        "phone": undefined,
        "postalCode": "24453",
        "region": undefined,
        "salutation": undefined,
        "state": undefined,
        "streetName": "dfdfds",
        "streetNumber": undefined,
        "title": undefined,
          },
          {
        "additionalAddressInfo": "dsfdsf",
        "additionalStreetInfo": undefined,
        "apartment": undefined,
        "building": undefined,
        "city": "cvdsfa",
        "company": undefined,
        "country": "GB",
        "custom": undefined,
        "department": undefined,
        "email": undefined,
        "externalId": undefined,
        "fax": undefined,
        "firstName": "sfsdf",
        "id": undefined,
        "key": "sam-smith-address-2",
        "lastName": "sfsdf",
        "mobile": undefined,
        "pOBox": undefined,
        "phone": undefined,
        "postalCode": "23243",
        "region": undefined,
        "salutation": undefined,
        "state": undefined,
        "streetName": "sfsdf",
        "streetNumber": undefined,
        "title": undefined,
      },
      {
        "additionalAddressInfo": undefined,
        "additionalStreetInfo": undefined,
        "apartment": undefined,
        "building": undefined,
        "city": "dfgsfg",
        "company": undefined,
        "country": "GB",
        "custom": undefined,
        "department": undefined,
        "email": undefined,
        "externalId": undefined,
        "fax": undefined,
        "firstName": "gfadg",
        "id": undefined,
        "key": "sam-smith-address-3",
        "lastName": "fdgsfgd",
        "mobile": undefined,
        "pOBox": undefined,
        "phone": undefined,
        "postalCode": "fdgsg",
        "region": undefined,
        "salutation": undefined,
        "state": undefined,
        "streetName": "4dfgfes",
        "streetNumber": undefined,
        "title": undefined,
      }, {
        "additionalAddressInfo": undefined,
        "additionalStreetInfo": undefined,
        "apartment": undefined,
        "building": undefined,
        "city": "dfafdsf",
        "company": undefined,
        "country": "GB",
        "custom": undefined,
        "department": undefined,
        "email": undefined,
        "externalId": undefined,
        "fax": undefined,
        "firstName": "dsfdsgf",
        "id": undefined,
        "key": "sam-smith-address-4",
        "lastName": "sdfdsf",
        "mobile": undefined,
        "pOBox": undefined,
        "phone": undefined,
        "postalCode": "43424",
        "region": undefined,
        "salutation": undefined,
        "state": undefined,
        "streetName": "sdfsdfsdf",
        "streetNumber": undefined,
        "title": undefined,
      }
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "sam.smith@example.com",
        "externalId": undefined,
        "firstName": "Sam",
        "isEmailVerified": false,
        "key": "sam-smith",
        "lastName": "Smith",
        "locale": undefined,
        "middleName": undefined,
        "password": "undefined",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  // it('should return a customer draft when built for GraphQL', () => {
  //   const customer = sampleGermany().buildGraphql<TCustomerDraftGraphql>();

  //   expect(customer).toMatchInlineSnapshot(`
  //     {
  //       "addresses": [
  //         {
  //           "additionalAddressInfo": undefined,
  //           "additionalStreetInfo": undefined,
  //           "apartment": undefined,
  //           "building": undefined,
  //           "city": "Sample Town",
  //           "company": undefined,
  //           "country": "DE",
  //           "custom": undefined,
  //           "department": undefined,
  //           "email": undefined,
  //           "externalId": undefined,
  //           "fax": undefined,
  //           "firstName": "Sample Customer",
  //           "id": undefined,
  //           "key": undefined,
  //           "lastName": "Germany",
  //           "mobile": undefined,
  //           "pOBox": undefined,
  //           "phone": undefined,
  //           "postalCode": "12345",
  //           "region": undefined,
  //           "salutation": undefined,
  //           "state": undefined,
  //           "streetName": "Sample Street",
  //           "streetNumber": "1",
  //           "title": undefined,
  //         },
  //       ],
  //       "anonymousCart": undefined,
  //       "anonymousId": undefined,
  //       "authenticationMode": "ExternalAuth",
  //       "billingAddresses": undefined,
  //       "companyName": undefined,
  //       "custom": undefined,
  //       "customerGroup": undefined,
  //       "customerNumber": undefined,
  //       "dateOfBirth": undefined,
  //       "defaultBillingAddress": undefined,
  //       "defaultShippingAddress": undefined,
  //       "email": "samplecustomer.germany@example.com",
  //       "externalId": undefined,
  //       "firstName": "Sample Customer",
  //       "isEmailVerified": false,
  //       "key": "123456",
  //       "lastName": "Germany",
  //       "locale": undefined,
  //       "middleName": undefined,
  //       "password": undefined,
  //       "salutation": undefined,
  //       "shippingAddresses": undefined,
  //       "stores": undefined,
  //       "title": undefined,
  //       "vatId": undefined,
  //     }
  //   `);
  // });
});
