import type { TCustomerDraft, TCustomerDraftGraphql } from '../../../types';
import sebastianFranklin from './sebastian-franklin';

describe('with the customer preset `sebastianFranklin`', () => {
  it('should return a draft when built for Default', () => {
    const customer = sebastianFranklin().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Durham",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sebastian",
            "id": undefined,
            "key": undefined,
            "lastName": "Franklin",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "27517",
            "region": undefined,
            "salutation": undefined,
            "state": "North Carolina",
            "streetName": "South Road",
            "streetNumber": "9",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "seb@example.com",
        "externalId": undefined,
        "firstName": "Sebastian",
        "isEmailVerified": undefined,
        "key": "sebastian-franklin",
        "lastName": "Franklin",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for Rest', () => {
    const customer = sebastianFranklin().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Durham",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sebastian",
            "id": undefined,
            "key": undefined,
            "lastName": "Franklin",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "27517",
            "region": undefined,
            "salutation": undefined,
            "state": "North Carolina",
            "streetName": "South Road",
            "streetNumber": "9",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "seb@example.com",
        "externalId": undefined,
        "firstName": "Sebastian",
        "isEmailVerified": undefined,
        "key": "sebastian-franklin",
        "lastName": "Franklin",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for GraphQL', () => {
    const customer = sebastianFranklin().build<TCustomerDraftGraphql>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Durham",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sebastian",
            "id": undefined,
            "key": undefined,
            "lastName": "Franklin",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "27517",
            "region": undefined,
            "salutation": undefined,
            "state": "North Carolina",
            "streetName": "South Road",
            "streetNumber": "9",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "seb@example.com",
        "externalId": undefined,
        "firstName": "Sebastian",
        "isEmailVerified": undefined,
        "key": "sebastian-franklin",
        "lastName": "Franklin",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
