import type { TCustomerDraft } from '../../../types';
import michaelWilliams from './michael-williams';

describe(`with michaelWilliams preset`, () => {
  it(`should return a michaelWilliams preset`, () => {
    const michaelWilliamsPreset = michaelWilliams().build<TCustomerDraft>();
    expect(michaelWilliamsPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Edinburgh",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Michael",
            "id": undefined,
            "key": undefined,
            "lastName": "Williams",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "EH2 2LE",
            "region": "Scotland",
            "salutation": undefined,
            "state": undefined,
            "streetName": "George Street",
            "streetNumber": "42",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "michael-williams@ehlt.com",
        "externalId": undefined,
        "firstName": "Michael",
        "isEmailVerified": true,
        "key": "michael-williams",
        "lastName": "Williams",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a michaelWilliams preset when built for graphql`, () => {
    const michaelWilliamsPresetGraphql =
      michaelWilliams().buildGraphql<TCustomerDraft>();
    expect(michaelWilliamsPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Edinburgh",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Michael",
            "id": undefined,
            "key": undefined,
            "lastName": "Williams",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "EH2 2LE",
            "region": "Scotland",
            "salutation": undefined,
            "state": undefined,
            "streetName": "George Street",
            "streetNumber": "42",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "michael-williams@ehlt.com",
        "externalId": undefined,
        "firstName": "Michael",
        "isEmailVerified": true,
        "key": "michael-williams",
        "lastName": "Williams",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
