import AssociateRole from '../builder';
import { ORDER_PERMISSIONS } from '../constants';

const withAllOrderPermissions = () =>
  AssociateRole().permissions([
    ORDER_PERMISSIONS.CREATE_MY_ORDERS_FROM_MY_CARTS,
    ORDER_PERMISSIONS.CREATE_ORDERS_FROM_OTHERS_CARTS,
    ORDER_PERMISSIONS.CREATE_MY_ORDERS_FROM_MY_QUOTES,
    ORDER_PERMISSIONS.CREATE_ORDERS_FROM_OTHERS_QUOTES,
    ORDER_PERMISSIONS.UPDATE_MY_ORDERS,
    ORDER_PERMISSIONS.UPDATE_OTHERS_ORDERS,
    ORDER_PERMISSIONS.VIEW_MY_ORDERS,
    ORDER_PERMISSIONS.VIEW_OTHERS_ORDERS,
  ]);

export default withAllOrderPermissions;
