const resourceTypeIds = {
  address: 'address',
  asset: 'asset',
  associateRole: 'associate-role',
  businessUnit: 'business-unit',
  cartDiscount: 'cart-discount',
  category: 'category',
  channel: 'channel',
  customer: 'customer',
  customerGroup: 'customer-group',
  customLineItem: 'custom-line-item',
  discountCode: 'discount-code',
  inventoryEntry: 'inventory-entry',
  lineItem: 'line-item',
  order: 'order',
  orderEdit: 'order-edit',
  orderDelivery: 'order-delivery',
  orderParcel: 'order-parcel',
  orderReturnItem: 'order-return-item',
  payment: 'payment',
  paymentInterfaceInteraction: 'payment-interface-interaction',
  productPrice: 'product-price',
  productSelection: 'product-selection',
  quote: 'quote',
  review: 'review',
  shipping: 'shipping',
  shippingMethod: 'shipping-method',
  shoppingList: 'shopping-list',
  shoppingListTextLineItem: 'shopping-list-text-line-item',
  standalonePrice: 'standalone-price',
  store: 'store',
  transaction: 'transaction',
} as const;

export { resourceTypeIds };
