import { TCartDraft } from '../../../types';
import sebastianFranklin01 from './sebastian-franklin-01';

describe('with the preset cart `sebastianFranklin01`', () => {
  it('should return a cart draft', () => {
    const cartDraft = sebastianFranklin01().build<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "the-good-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it('without customer ID, should return a cart draft', () => {
    const cartDraft = sebastianFranklin01().build<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "the-good-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it('should return a cart draft when build for GraphQL', () => {
    const cartDraft = sebastianFranklin01().buildGraphql<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "NC",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "__typename": "Reference",
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "__typename": "Reference",
          "key": "the-good-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
