import type { TCustomerDraft, TCustomerDraftGraphql } from '../../../types';
import jenniferRobinson from './jennifer-robinson';

describe('with the customer preset `jenniferRobinson`', () => {
  it('should return a draft when built for Default', () => {
    const customer = jenniferRobinson().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "New York City",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Robinson",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "10001",
            "region": undefined,
            "salutation": undefined,
            "state": "New York",
            "streetName": "Second Street",
            "streetNumber": "15",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.com",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": true,
        "key": "jennifer-robinson",
        "lastName": "Robinson",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for Rest', () => {
    const customer = jenniferRobinson().build<TCustomerDraft>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "New York City",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Robinson",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "10001",
            "region": undefined,
            "salutation": undefined,
            "state": "New York",
            "streetName": "Second Street",
            "streetNumber": "15",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.com",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": true,
        "key": "jennifer-robinson",
        "lastName": "Robinson",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it('should return a draft when built for GraphQL', () => {
    const customer = jenniferRobinson().build<TCustomerDraftGraphql>();

    expect(customer).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "New York City",
            "company": undefined,
            "country": "US",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Jennifer",
            "id": undefined,
            "key": undefined,
            "lastName": "Robinson",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "10001",
            "region": undefined,
            "salutation": undefined,
            "state": "New York",
            "streetName": "Second Street",
            "streetNumber": "15",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "jen@example.com",
        "externalId": undefined,
        "firstName": "Jennifer",
        "isEmailVerified": true,
        "key": "jennifer-robinson",
        "lastName": "Robinson",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
