import { TCartDraft } from '../../../types';
import sampleGermany02 from './sample-germany-02';

describe('with the preset cart `sampleGermany02`', () => {
  it('should return a cart discount draft', () => {
    const cartDraft = sampleGermany02().build<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "DE",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "samplecustomer.germany@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": [
          "BOGO",
        ],
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "mary-02-cart",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 2,
            "shippingDetails": undefined,
            "sku": "118718",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": undefined,
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": undefined,
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it('should return a cart discount draft when build for GraphQL', () => {
    const cartDraft = sampleGermany02().buildGraphql<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "DE",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "samplecustomer.germany@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": [
          "BOGO",
        ],
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "mary-02-cart",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 2,
            "shippingDetails": undefined,
            "sku": "118718",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": undefined,
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": undefined,
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
