import type { TCartDraftGraphql, TCartDraftRest } from '../../../types';
import * as presets from './sample-germany-01';

describe(`with sampleGermany01 preset`, () => {
  it(`should return a sampleGermany01 preset when built for rest`, () => {
    const sampleGermany01Preset = presets.restPreset().build();
    expect(sampleGermany01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "DE",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "samplecustomer.germany@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "sample-germany-01-cart",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "perMethodExternalTaxRate": [],
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "752502",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "shipping-europe",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "sample_store_one",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sampleGermany01 preset when built for graphql`, () => {
    const sampleGermany01Preset = presets.graphqlPreset().build();
    expect(sampleGermany01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "DE",
        "currency": "EUR",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "samplecustomer.germany@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": undefined,
        "itemShippingAddresses": undefined,
        "key": "sample-germany-01-cart",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "752502",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Sample Town",
          "company": undefined,
          "country": "DE",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sample Customer",
          "id": undefined,
          "key": undefined,
          "lastName": "Germany",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "12345",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Sample Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "shipping-europe",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "sample_store_one",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sampleGermany01 preset when built for legacy rest`, () => {
    const sampleGermany01Preset = presets
      .compatPreset()
      .buildRest<TCartDraftRest>();
    expect(sampleGermany01Preset).toMatchInlineSnapshot(`
        {
          "anonymousId": undefined,
          "billingAddress": {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Sample Town",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sample Customer",
            "id": undefined,
            "key": undefined,
            "lastName": "Germany",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "12345",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Sample Street",
            "streetNumber": "1",
            "title": undefined,
          },
          "businessUnit": undefined,
          "country": "DE",
          "currency": "EUR",
          "custom": undefined,
          "customLineItems": undefined,
          "customShipping": undefined,
          "customerEmail": "samplecustomer.germany@example.com",
          "customerGroup": undefined,
          "customerId": undefined,
          "deleteDaysAfterLastModification": undefined,
          "discountCodes": undefined,
          "externalTaxRateForShippingMethod": undefined,
          "inventoryMode": undefined,
          "itemShippingAddresses": undefined,
          "key": "sample-germany-01-cart",
          "lineItems": [
            {
              "addedAt": undefined,
              "custom": undefined,
              "distributionChannel": undefined,
              "externalPrice": undefined,
              "externalTaxRate": undefined,
              "externalTotalPrice": undefined,
              "inventoryMode": undefined,
              "key": undefined,
              "perMethodExternalTaxRate": [],
              "productId": undefined,
              "quantity": 1,
              "shippingDetails": undefined,
              "sku": "752502",
              "supplyChannel": undefined,
              "variantId": undefined,
            },
          ],
          "locale": undefined,
          "origin": "Merchant",
          "shipping": undefined,
          "shippingAddress": {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Sample Town",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sample Customer",
            "id": undefined,
            "key": undefined,
            "lastName": "Germany",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "12345",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Sample Street",
            "streetNumber": "1",
            "title": undefined,
          },
          "shippingMethod": {
            "key": "shipping-europe",
            "typeId": "shipping-method",
          },
          "shippingMode": undefined,
          "shippingRateInput": undefined,
          "store": {
            "key": "sample_store_one",
            "typeId": "store",
          },
          "taxCalculationMode": undefined,
          "taxMode": undefined,
          "taxRoundingMode": undefined,
        }
      `);
  });

  it(`should return a sampleGermany01 preset when built for legacy graphql`, () => {
    const sampleGermany01Preset = presets
      .compatPreset()
      .buildGraphql<TCartDraftGraphql>();
    expect(sampleGermany01Preset).toMatchInlineSnapshot(`
        {
          "anonymousId": undefined,
          "billingAddress": {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Sample Town",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sample Customer",
            "id": undefined,
            "key": undefined,
            "lastName": "Germany",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "12345",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Sample Street",
            "streetNumber": "1",
            "title": undefined,
          },
          "businessUnit": undefined,
          "country": "DE",
          "currency": "EUR",
          "custom": undefined,
          "customLineItems": undefined,
          "customShipping": undefined,
          "customerEmail": "samplecustomer.germany@example.com",
          "customerGroup": undefined,
          "customerId": undefined,
          "deleteDaysAfterLastModification": undefined,
          "discountCodes": undefined,
          "externalTaxRateForShippingMethod": undefined,
          "inventoryMode": undefined,
          "itemShippingAddresses": undefined,
          "key": "sample-germany-01-cart",
          "lineItems": [
            {
              "addedAt": undefined,
              "custom": undefined,
              "distributionChannel": undefined,
              "externalPrice": undefined,
              "externalTaxRate": undefined,
              "externalTotalPrice": undefined,
              "inventoryMode": undefined,
              "key": undefined,
              "productId": undefined,
              "quantity": 1,
              "shippingDetails": undefined,
              "sku": "752502",
              "supplyChannel": undefined,
              "variantId": undefined,
            },
          ],
          "locale": undefined,
          "origin": "Merchant",
          "shipping": undefined,
          "shippingAddress": {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Sample Town",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Sample Customer",
            "id": undefined,
            "key": undefined,
            "lastName": "Germany",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "12345",
            "region": undefined,
            "salutation": undefined,
            "state": undefined,
            "streetName": "Sample Street",
            "streetNumber": "1",
            "title": undefined,
          },
          "shippingMethod": {
            "key": "shipping-europe",
            "typeId": "shipping-method",
          },
          "shippingMode": undefined,
          "shippingRateInput": undefined,
          "store": {
            "key": "sample_store_one",
            "typeId": "store",
          },
          "taxCalculationMode": undefined,
          "taxMode": undefined,
          "taxRoundingMode": undefined,
        }
      `);
  });
});
