import type { TCartDraftGraphql, TCartDraftRest } from '../../../types';
import * as presets from './sebastian-smith-01';

describe(`with sebastianSmith01 preset`, () => {
  it(`should return a sebastianSmith01 preset when built for rest`, () => {
    const sebastianSmith01Preset = presets.restPreset().build();
    expect(sebastianSmith01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.uk",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-smith-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "RCQB-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MLP-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "GPC-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MTSS-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "express-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianSmith01 preset when built for graphql`, () => {
    const sebastianSmith01Preset = presets.graphqlPreset().build();
    expect(sebastianSmith01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.uk",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-smith-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "RCQB-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MLP-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "GPC-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MTSS-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "express-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianSmith01 preset when built for legacy rest`, () => {
    const sebastianSmith01Preset = presets
      .compatPreset()
      .buildRest<TCartDraftRest>();
    expect(sebastianSmith01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.uk",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-smith-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "RCQB-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MLP-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "GPC-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MTSS-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "express-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianSmith01 preset when built for legacy graphql`, () => {
    const sebastianSmith01Preset = presets
      .compatPreset()
      .buildGraphql<TCartDraftGraphql>();
    expect(sebastianSmith01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "GB",
        "currency": "GBP",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.uk",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-smith-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "RCQB-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MLP-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "GPC-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "productId": undefined,
            "quantity": 1,
            "shippingDetails": undefined,
            "sku": "MTSS-01",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Fareham",
          "company": undefined,
          "country": "GB",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Smith",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "PO167GZ",
          "region": undefined,
          "salutation": undefined,
          "state": undefined,
          "streetName": "Center Street",
          "streetNumber": "1",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "express-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
