import type { TCartDraftGraphql, TCartDraftRest } from '../../../types';
import * as presets from './sebastian-franklin-01';

describe(`with sebastianFranklin01 preset`, () => {
  it(`should return a sebastianFranklin01 preset when built for rest`, () => {
    const sebastianFranklin01Preset = presets.restPreset().build();
    expect(sebastianFranklin01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "perMethodExternalTaxRate": [],
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianFranklin01 preset when built for graphql`, () => {
    const sebastianFranklin01Preset = presets.graphqlPreset().build();
    expect(sebastianFranklin01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianFranklin01 preset when built for legacy rest`, () => {
    const sebastianFranklin01Preset = presets
      .compatPreset()
      .buildRest<TCartDraftRest>();
    expect(sebastianFranklin01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "perMethodExternalTaxRate": [],
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });

  it(`should return a sebastianFranklin01 preset when built for legacy graphql`, () => {
    const sebastianFranklin01Preset = presets
      .compatPreset()
      .buildGraphql<TCartDraftGraphql>();
    expect(sebastianFranklin01Preset).toMatchInlineSnapshot(`
      {
        "anonymousId": undefined,
        "billingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "businessUnit": undefined,
        "country": "US",
        "currency": "USD",
        "custom": undefined,
        "customLineItems": undefined,
        "customShipping": undefined,
        "customerEmail": "seb@example.com",
        "customerGroup": undefined,
        "customerId": undefined,
        "deleteDaysAfterLastModification": undefined,
        "discountCodes": undefined,
        "externalTaxRateForShippingMethod": undefined,
        "inventoryMode": "None",
        "itemShippingAddresses": undefined,
        "key": "sebastian-franklin-01",
        "lineItems": [
          {
            "addedAt": undefined,
            "custom": undefined,
            "distributionChannel": undefined,
            "externalPrice": undefined,
            "externalTaxRate": undefined,
            "externalTotalPrice": undefined,
            "inventoryMode": undefined,
            "key": undefined,
            "productId": undefined,
            "quantity": 20,
            "shippingDetails": undefined,
            "sku": "FLAS-094",
            "supplyChannel": undefined,
            "variantId": undefined,
          },
        ],
        "locale": undefined,
        "origin": "Merchant",
        "shipping": undefined,
        "shippingAddress": {
          "additionalAddressInfo": undefined,
          "additionalStreetInfo": undefined,
          "apartment": undefined,
          "building": undefined,
          "city": "Durham",
          "company": undefined,
          "country": "US",
          "custom": undefined,
          "department": undefined,
          "email": undefined,
          "externalId": undefined,
          "fax": undefined,
          "firstName": "Sebastian",
          "id": undefined,
          "key": undefined,
          "lastName": "Franklin",
          "mobile": undefined,
          "pOBox": undefined,
          "phone": undefined,
          "postalCode": "27517",
          "region": undefined,
          "salutation": undefined,
          "state": "North Carolina",
          "streetName": "South Road",
          "streetNumber": "9",
          "title": undefined,
        },
        "shippingMethod": {
          "key": "us-delivery",
          "typeId": "shipping-method",
        },
        "shippingMode": undefined,
        "shippingRateInput": undefined,
        "store": {
          "key": "b2c-retail-store",
          "typeId": "store",
        },
        "taxCalculationMode": undefined,
        "taxMode": undefined,
        "taxRoundingMode": undefined,
      }
    `);
  });
});
