import type { TCartDraft } from '../../../types';
import sebastianMueller01 from './sebastian-mueller-01';

describe('with the preset cart `sebastianMueller01`', () => {
  it('should return a cart draft', () => {
    const cartDraft = sebastianMueller01().build<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
{
  "anonymousId": undefined,
  "billingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "businessUnit": undefined,
  "country": "DE",
  "currency": "EUR",
  "custom": undefined,
  "customLineItems": undefined,
  "customShipping": undefined,
  "customerEmail": "seb@example.de",
  "customerGroup": undefined,
  "customerId": undefined,
  "deleteDaysAfterLastModification": undefined,
  "discountCodes": undefined,
  "externalTaxRateForShippingMethod": undefined,
  "inventoryMode": undefined,
  "itemShippingAddresses": undefined,
  "key": "sebastian-mueller-01",
  "lineItems": [
    {
      "addedAt": undefined,
      "custom": undefined,
      "distributionChannel": undefined,
      "externalPrice": undefined,
      "externalTaxRate": undefined,
      "externalTotalPrice": undefined,
      "inventoryMode": undefined,
      "productId": undefined,
      "quantity": 1,
      "shippingDetails": undefined,
      "sku": "TLSS-01",
      "supplyChannel": undefined,
      "variantId": undefined,
    },
  ],
  "locale": undefined,
  "origin": "Merchant",
  "shipping": undefined,
  "shippingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "shippingMethod": {
    "key": "standard-delivery",
    "typeId": "shipping-method",
  },
  "shippingMode": undefined,
  "shippingRateInput": undefined,
  "store": {
    "key": "b2c-retail-store",
    "typeId": "store",
  },
  "taxCalculationMode": undefined,
  "taxMode": undefined,
  "taxRoundingMode": undefined,
}
`);
  });

  it('without customer ID, should return a cart draft', () => {
    const cartDraft = sebastianMueller01().build<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
{
  "anonymousId": undefined,
  "billingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "businessUnit": undefined,
  "country": "DE",
  "currency": "EUR",
  "custom": undefined,
  "customLineItems": undefined,
  "customShipping": undefined,
  "customerEmail": "seb@example.de",
  "customerGroup": undefined,
  "customerId": undefined,
  "deleteDaysAfterLastModification": undefined,
  "discountCodes": undefined,
  "externalTaxRateForShippingMethod": undefined,
  "inventoryMode": undefined,
  "itemShippingAddresses": undefined,
  "key": "sebastian-mueller-01",
  "lineItems": [
    {
      "addedAt": undefined,
      "custom": undefined,
      "distributionChannel": undefined,
      "externalPrice": undefined,
      "externalTaxRate": undefined,
      "externalTotalPrice": undefined,
      "inventoryMode": undefined,
      "productId": undefined,
      "quantity": 1,
      "shippingDetails": undefined,
      "sku": "TLSS-01",
      "supplyChannel": undefined,
      "variantId": undefined,
    },
  ],
  "locale": undefined,
  "origin": "Merchant",
  "shipping": undefined,
  "shippingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "shippingMethod": {
    "key": "standard-delivery",
    "typeId": "shipping-method",
  },
  "shippingMode": undefined,
  "shippingRateInput": undefined,
  "store": {
    "key": "b2c-retail-store",
    "typeId": "store",
  },
  "taxCalculationMode": undefined,
  "taxMode": undefined,
  "taxRoundingMode": undefined,
}
`);
  });

  it('should return a cart draft when build for GraphQL', () => {
    const cartDraft = sebastianMueller01().buildGraphql<TCartDraft>();

    expect(cartDraft).toMatchInlineSnapshot(`
{
  "anonymousId": undefined,
  "billingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "businessUnit": undefined,
  "country": "DE",
  "currency": "EUR",
  "custom": undefined,
  "customLineItems": undefined,
  "customShipping": undefined,
  "customerEmail": "seb@example.de",
  "customerGroup": undefined,
  "customerId": undefined,
  "deleteDaysAfterLastModification": undefined,
  "discountCodes": undefined,
  "externalTaxRateForShippingMethod": undefined,
  "inventoryMode": undefined,
  "itemShippingAddresses": undefined,
  "key": "sebastian-mueller-01",
  "lineItems": [
    {
      "addedAt": undefined,
      "custom": undefined,
      "distributionChannel": undefined,
      "externalPrice": undefined,
      "externalTaxRate": undefined,
      "externalTotalPrice": undefined,
      "inventoryMode": undefined,
      "productId": undefined,
      "quantity": 1,
      "shippingDetails": undefined,
      "sku": "TLSS-01",
      "supplyChannel": undefined,
      "variantId": undefined,
    },
  ],
  "locale": undefined,
  "origin": "Merchant",
  "shipping": undefined,
  "shippingAddress": {
    "additionalAddressInfo": undefined,
    "additionalStreetInfo": undefined,
    "apartment": undefined,
    "building": undefined,
    "city": "München",
    "company": undefined,
    "country": "DE",
    "custom": undefined,
    "department": undefined,
    "email": undefined,
    "externalId": undefined,
    "fax": undefined,
    "firstName": "Sebastian",
    "id": undefined,
    "key": undefined,
    "lastName": "Müller",
    "mobile": undefined,
    "pOBox": undefined,
    "phone": undefined,
    "postalCode": "80331",
    "region": undefined,
    "salutation": undefined,
    "state": undefined,
    "streetName": "Schulstrasse",
    "streetNumber": "12",
    "title": undefined,
  },
  "shippingMethod": {
    "key": "standard-delivery",
    "typeId": "shipping-method",
  },
  "shippingMode": undefined,
  "shippingRateInput": undefined,
  "store": {
    "key": "b2c-retail-store",
    "typeId": "store",
  },
  "taxCalculationMode": undefined,
  "taxMode": undefined,
  "taxRoundingMode": undefined,
}
`);
  });
});
