import { TBuilder } from '@/core';
import { LocalizedStringDraft } from '../../../../../commons';
import {
  AttributeDefinitionDraft,
  AttributeDefinitionDraftGraphql,
  AttributeDefinitionDraftRest,
  AttributeEnumTypeDraft,
  AttributeEnumTypeDraftGraphql,
  AttributeEnumTypeDraftRest,
  AttributePlainEnumValueDraft,
  AttributePlainEnumValueDraftGraphql,
  AttributePlainEnumValueDraftRest,
} from '../../../../index';
import {
  TProductTypeDraft,
  TProductTypeDraftGraphql,
  TProductTypeDraftRest,
} from '../../../types';
import {
  ProductTypeDraft,
  ProductTypeDraftGraphql,
  ProductTypeDraftRest,
} from '../../index';

export const restPreset = (): TBuilder<TProductTypeDraftRest> =>
  ProductTypeDraftRest.presets
    .empty()
    .key('shirts')
    .name('Shirts')
    .description('Shirts')
    .attributes([
      AttributeDefinitionDraftRest.presets
        .empty()
        .name('size')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraftRest.random().values([
            AttributePlainEnumValueDraftRest.random()
              .key('Small')
              .label('Small'),
            AttributePlainEnumValueDraftRest.random()
              .key('Medium')
              .label('Medium'),
            AttributePlainEnumValueDraftRest.random()
              .key('Large')
              .label('Large'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraftRest.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(
          AttributeDefinitionDraftRest.constants.inputHints.SingleLine
        ),
      AttributeDefinitionDraftRest.presets
        .empty()
        .name('color')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraftRest.random().values([
            AttributePlainEnumValueDraftRest.random().key('Red').label('Red'),
            AttributePlainEnumValueDraftRest.random()
              .key('Green')
              .label('Green'),
            AttributePlainEnumValueDraftRest.random()
              .key('Purple')
              .label('Purple'),
            AttributePlainEnumValueDraftRest.random()
              .key('Multi-Color')
              .label('Multi-Color'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraftRest.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(
          AttributeDefinitionDraftRest.constants.inputHints.SingleLine
        ),
    ]);

export const graphqlPreset = (): TBuilder<TProductTypeDraftGraphql> =>
  ProductTypeDraftGraphql.presets
    .empty()
    .key('shirts')
    .name('Shirts')
    .description('Shirts')
    .attributeDefinitions([
      AttributeDefinitionDraftGraphql.presets
        .empty()
        .name('size')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraftGraphql.random().values([
            AttributePlainEnumValueDraftGraphql.random()
              .key('Small')
              .label('Small'),
            AttributePlainEnumValueDraftGraphql.random()
              .key('Medium')
              .label('Medium'),
            AttributePlainEnumValueDraftGraphql.random()
              .key('Large')
              .label('Large'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraftGraphql.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(
          AttributeDefinitionDraftGraphql.constants.inputHints.SingleLine
        ),
      AttributeDefinitionDraftGraphql.presets
        .empty()
        .name('color')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraftGraphql.random().values([
            AttributePlainEnumValueDraftGraphql.random()
              .key('Red')
              .label('Red'),
            AttributePlainEnumValueDraftGraphql.random()
              .key('Green')
              .label('Green'),
            AttributePlainEnumValueDraftGraphql.random()
              .key('Purple')
              .label('Purple'),
            AttributePlainEnumValueDraftGraphql.random()
              .key('Multi-Color')
              .label('Multi-Color'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraftGraphql.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(
          AttributeDefinitionDraftGraphql.constants.inputHints.SingleLine
        ),
    ]);

export const compatPreset = (): TBuilder<TProductTypeDraft> =>
  ProductTypeDraft.presets
    .empty()
    .key('shirts')
    .name('Shirts')
    .description('Shirts')
    .attributes([
      AttributeDefinitionDraft.presets
        .empty()
        .name('size')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Size'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraft.random().values([
            AttributePlainEnumValueDraft.random().key('Small').label('Small'),
            AttributePlainEnumValueDraft.random().key('Medium').label('Medium'),
            AttributePlainEnumValueDraft.random().key('Large').label('Large'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraft.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(AttributeDefinitionDraft.constants.inputHints.SingleLine),
      AttributeDefinitionDraft.presets
        .empty()
        .name('color')
        .label(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .inputTip(LocalizedStringDraft.presets.empty()['en-US']('Color'))
        .isRequired(false)
        .type(
          AttributeEnumTypeDraft.random().values([
            AttributePlainEnumValueDraft.random().key('Red').label('Red'),
            AttributePlainEnumValueDraft.random().key('Green').label('Green'),
            AttributePlainEnumValueDraft.random().key('Purple').label('Purple'),
            AttributePlainEnumValueDraft.random()
              .key('Multi-Color')
              .label('Multi-Color'),
          ])
        )
        .attributeConstraint(
          AttributeDefinitionDraft.constants.attributeConstraints
            .CombinationUnique
        )
        .isSearchable(false)
        .inputHint(AttributeDefinitionDraft.constants.inputHints.SingleLine),
    ]);
