import type { TCustomerDraft } from '../../../types';
import lukasSchmidt from './lukas-schmidt';

describe(`with lukasSchmidt preset`, () => {
  it(`should return a lukasSchmidt preset`, () => {
    const lukasSchmidtPreset = lukasSchmidt().build<TCustomerDraft>();
    expect(lukasSchmidtPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Stuttgart",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Lukas",
            "id": undefined,
            "key": undefined,
            "lastName": "Schmidt",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "70173",
            "region": undefined,
            "salutation": undefined,
            "state": "Baden-Württemberg",
            "streetName": "Königstraße",
            "streetNumber": "50",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "lukas-schmidt@ltsl.com",
        "externalId": undefined,
        "firstName": "Lukas",
        "isEmailVerified": true,
        "key": "lukas-schmidt",
        "lastName": "Schmidt",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a lukasSchmidt preset when built for graphql`, () => {
    const lukasSchmidtPresetGraphql =
      lukasSchmidt().buildGraphql<TCustomerDraft>();
    expect(lukasSchmidtPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "Stuttgart",
            "company": undefined,
            "country": "DE",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Lukas",
            "id": undefined,
            "key": undefined,
            "lastName": "Schmidt",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "70173",
            "region": undefined,
            "salutation": undefined,
            "state": "Baden-Württemberg",
            "streetName": "Königstraße",
            "streetNumber": "50",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "lukas-schmidt@ltsl.com",
        "externalId": undefined,
        "firstName": "Lukas",
        "isEmailVerified": true,
        "key": "lukas-schmidt",
        "lastName": "Schmidt",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
