import type { TCustomerDraft } from '../../../types';
import oliverSmith from './oliver-smith';

describe(`with oliverSmith preset`, () => {
  it(`should return a oliverSmith preset`, () => {
    const oliverSmithPreset = oliverSmith().build<TCustomerDraft>();
    expect(oliverSmithPreset).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "London",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Oliver",
            "id": undefined,
            "key": undefined,
            "lastName": "Smith",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "SW1E 5JL",
            "region": "Greater London",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Victoria Street",
            "streetNumber": "100",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "oliver-smith@ltsl.com",
        "externalId": undefined,
        "firstName": "Oliver",
        "isEmailVerified": true,
        "key": "oliver-smith",
        "lastName": "Smith",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });

  it(`should return a oliverSmith preset when built for graphql`, () => {
    const oliverSmithPresetGraphql =
      oliverSmith().buildGraphql<TCustomerDraft>();
    expect(oliverSmithPresetGraphql).toMatchInlineSnapshot(`
      {
        "addresses": [
          {
            "additionalAddressInfo": undefined,
            "additionalStreetInfo": undefined,
            "apartment": undefined,
            "building": undefined,
            "city": "London",
            "company": undefined,
            "country": "GB",
            "custom": undefined,
            "department": undefined,
            "email": undefined,
            "externalId": undefined,
            "fax": undefined,
            "firstName": "Oliver",
            "id": undefined,
            "key": undefined,
            "lastName": "Smith",
            "mobile": undefined,
            "pOBox": undefined,
            "phone": undefined,
            "postalCode": "SW1E 5JL",
            "region": "Greater London",
            "salutation": undefined,
            "state": undefined,
            "streetName": "Victoria Street",
            "streetNumber": "100",
            "title": undefined,
          },
        ],
        "anonymousCart": undefined,
        "anonymousId": undefined,
        "authenticationMode": "Password",
        "billingAddresses": undefined,
        "companyName": undefined,
        "custom": undefined,
        "customerGroup": undefined,
        "customerNumber": undefined,
        "dateOfBirth": undefined,
        "defaultBillingAddress": undefined,
        "defaultShippingAddress": undefined,
        "email": "oliver-smith@ltsl.com",
        "externalId": undefined,
        "firstName": "Oliver",
        "isEmailVerified": true,
        "key": "oliver-smith",
        "lastName": "Smith",
        "locale": undefined,
        "middleName": undefined,
        "password": "123",
        "salutation": undefined,
        "shippingAddresses": undefined,
        "stores": undefined,
        "title": undefined,
        "vatId": undefined,
      }
    `);
  });
});
