name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        id: pnpm-install
        with:
          run_install: false

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Building packages
        run: pnpm build

      - name: Running static type checking
        run: pnpm typecheck

      - name: Running linters and tests
        run: pnpm jest --projects jest.{eslint,test}.config.js --reporters jest-silent-reporter
        env:
          CI: true
