name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        id: pnpm-install
        with:
          run_install: false

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Building packages
        run: pnpm build

      - name: Running static type checking
        run: pnpm typecheck

      - name: Running linters and tests
        run: pnpm jest --projects jest.{eslint,test}.config.js --reporters jest-silent-reporter
        env:
          CI: true
